/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FinalizarCompraRouteImport } from './routes/finalizar-compra'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MinhasComprasRouteImport } from './routes/minhas-compras'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as SobreASacolinhaRouteImport } from './routes/sobre-a-sacolinha'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminEntrarRouteImport } from './routes/admin/entrar'
import { Route as PedidoPedidoIdRouteImport } from './routes/pedido.$pedidoId'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedBannersRouteImport } from './routes/admin/_authed/banners'
import { Route as AdminAuthedClientesRouteImport } from './routes/admin/_authed/clientes'
import { Route as AdminAuthedCuponsRouteImport } from './routes/admin/_authed/cupons'
import { Route as AdminAuthedPedidosRouteImport } from './routes/admin/_authed/pedidos'
import { Route as AdminAuthedProdutosRouteImport } from './routes/admin/_authed/produtos'
import { Route as AdminAuthedVitrineRouteImport } from './routes/admin/_authed/vitrine'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizarCompraRoute = FinalizarCompraRouteImport.update({
  id: '/finalizar-compra',
  path: '/finalizar-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasComprasRoute = MinhasComprasRouteImport.update({
  id: '/minhas-compras',
  path: '/minhas-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreASacolinhaRoute = SobreASacolinhaRouteImport.update({
  id: '/sobre-a-sacolinha',
  path: '/sobre-a-sacolinha',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin/entrar',
  path: '/admin/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoPedidoIdRoute = PedidoPedidoIdRouteImport.update({
  id: '/pedido/$pedidoId',
  path: '/pedido/$pedidoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedBannersRoute = AdminAuthedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedClientesRoute = AdminAuthedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedCuponsRoute = AdminAuthedCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPedidosRoute = AdminAuthedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProdutosRoute = AdminAuthedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedVitrineRoute = AdminAuthedVitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-a-sacolinha': typeof SobreASacolinhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/entrar': typeof AdminEntrarRoute
  '/pedido/$pedidoId': typeof PedidoPedidoIdRoute
  '/admin/banners': typeof AdminAuthedBannersRoute
  '/admin/clientes': typeof AdminAuthedClientesRoute
  '/admin/cupons': typeof AdminAuthedCuponsRoute
  '/admin/pedidos': typeof AdminAuthedPedidosRoute
  '/admin/produtos': typeof AdminAuthedProdutosRoute
  '/admin/vitrine': typeof AdminAuthedVitrineRoute
  '/admin/': typeof AdminAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-a-sacolinha': typeof SobreASacolinhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin/entrar': typeof AdminEntrarRoute
  '/pedido/$pedidoId': typeof PedidoPedidoIdRoute
  '/admin/banners': typeof AdminAuthedBannersRoute
  '/admin/clientes': typeof AdminAuthedClientesRoute
  '/admin/cupons': typeof AdminAuthedCuponsRoute
  '/admin/pedidos': typeof AdminAuthedPedidosRoute
  '/admin/produtos': typeof AdminAuthedProdutosRoute
  '/admin/vitrine': typeof AdminAuthedVitrineRoute
  '/admin': typeof AdminAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-a-sacolinha': typeof SobreASacolinhaRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/entrar': typeof AdminEntrarRoute
  '/pedido/$pedidoId': typeof PedidoPedidoIdRoute
  '/admin/_authed/banners': typeof AdminAuthedBannersRoute
  '/admin/_authed/clientes': typeof AdminAuthedClientesRoute
  '/admin/_authed/cupons': typeof AdminAuthedCuponsRoute
  '/admin/_authed/pedidos': typeof AdminAuthedPedidosRoute
  '/admin/_authed/produtos': typeof AdminAuthedProdutosRoute
  '/admin/_authed/vitrine': typeof AdminAuthedVitrineRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/criar-conta'
    | '/entrar'
    | '/finalizar-compra'
    | '/minha-conta'
    | '/minhas-compras'
    | '/produtos'
    | '/sobre-a-sacolinha'
    | '/verificar-email'
    | '/admin'
    | '/admin/entrar'
    | '/pedido/$pedidoId'
    | '/admin/banners'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/vitrine'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/criar-conta'
    | '/entrar'
    | '/finalizar-compra'
    | '/minha-conta'
    | '/minhas-compras'
    | '/produtos'
    | '/sobre-a-sacolinha'
    | '/verificar-email'
    | '/admin/entrar'
    | '/pedido/$pedidoId'
    | '/admin/banners'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/vitrine'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/criar-conta'
    | '/entrar'
    | '/finalizar-compra'
    | '/minha-conta'
    | '/minhas-compras'
    | '/produtos'
    | '/sobre-a-sacolinha'
    | '/verificar-email'
    | '/admin/_authed'
    | '/admin/entrar'
    | '/pedido/$pedidoId'
    | '/admin/_authed/banners'
    | '/admin/_authed/clientes'
    | '/admin/_authed/cupons'
    | '/admin/_authed/pedidos'
    | '/admin/_authed/produtos'
    | '/admin/_authed/vitrine'
    | '/admin/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  FinalizarCompraRoute: typeof FinalizarCompraRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MinhasComprasRoute: typeof MinhasComprasRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreASacolinhaRoute: typeof SobreASacolinhaRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminEntrarRoute: typeof AdminEntrarRoute
  PedidoPedidoIdRoute: typeof PedidoPedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizar-compra': {
      id: '/finalizar-compra'
      path: '/finalizar-compra'
      fullPath: '/finalizar-compra'
      preLoaderRoute: typeof FinalizarCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-compras': {
      id: '/minhas-compras'
      path: '/minhas-compras'
      fullPath: '/minhas-compras'
      preLoaderRoute: typeof MinhasComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-a-sacolinha': {
      id: '/sobre-a-sacolinha'
      path: '/sobre-a-sacolinha'
      fullPath: '/sobre-a-sacolinha'
      preLoaderRoute: typeof SobreASacolinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entrar': {
      id: '/admin/entrar'
      path: '/admin/entrar'
      fullPath: '/admin/entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$pedidoId': {
      id: '/pedido/$pedidoId'
      path: '/pedido/$pedidoId'
      fullPath: '/pedido/$pedidoId'
      preLoaderRoute: typeof PedidoPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/banners': {
      id: '/admin/_authed/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAuthedBannersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/clientes': {
      id: '/admin/_authed/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminAuthedClientesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/cupons': {
      id: '/admin/_authed/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminAuthedCuponsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/pedidos': {
      id: '/admin/_authed/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminAuthedPedidosRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/produtos': {
      id: '/admin/_authed/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminAuthedProdutosRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vitrine': {
      id: '/admin/_authed/vitrine'
      path: '/vitrine'
      fullPath: '/admin/vitrine'
      preLoaderRoute: typeof AdminAuthedVitrineRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedBannersRoute: typeof AdminAuthedBannersRoute
  AdminAuthedClientesRoute: typeof AdminAuthedClientesRoute
  AdminAuthedCuponsRoute: typeof AdminAuthedCuponsRoute
  AdminAuthedPedidosRoute: typeof AdminAuthedPedidosRoute
  AdminAuthedProdutosRoute: typeof AdminAuthedProdutosRoute
  AdminAuthedVitrineRoute: typeof AdminAuthedVitrineRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedBannersRoute: AdminAuthedBannersRoute,
  AdminAuthedClientesRoute: AdminAuthedClientesRoute,
  AdminAuthedCuponsRoute: AdminAuthedCuponsRoute,
  AdminAuthedPedidosRoute: AdminAuthedPedidosRoute,
  AdminAuthedProdutosRoute: AdminAuthedProdutosRoute,
  AdminAuthedVitrineRoute: AdminAuthedVitrineRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  FinalizarCompraRoute: FinalizarCompraRoute,
  MinhaContaRoute: MinhaContaRoute,
  MinhasComprasRoute: MinhasComprasRoute,
  ProdutosRoute: ProdutosRoute,
  SobreASacolinhaRoute: SobreASacolinhaRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminEntrarRoute: AdminEntrarRoute,
  PedidoPedidoIdRoute: PedidoPedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
